[book]
authors = ["Junrui Liu"]
language = "en"
multilingual = false
src = "src"
title = "The Patina Programming Language"

[output.html]
mathjax-support = true
theme = "theme" # the name of the directory you put hljs in